# Generated by Django 5.0.7 on 2024-08-05 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('gloss', models.TextField()),
                ('translation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GrammarFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('algorithm', models.CharField(max_length=100)),
                ('other_preferences', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_data', models.TextField()),
                ('grammar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chunker.grammar')),
            ],
        ),
        migrations.AddField(
            model_name='grammar',
            name='grammar_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chunker.grammarfile'),
        ),
    ]
